# Example configuration for the replace command
# This shows all available options

# Patterns to search for (regex supported)
patterns:
  # - "TODO"
  # - "FIXME"
  # - "console\\.log"
  # - "print\\(.*\\)"  # Python print statements

# Replacements for each pattern (use null to delete the next line)
replacements:
  # - "[DONE]"        # Replace TODO with [DONE]
  # - "[RESOLVED]"    # Replace FIXME with [RESOLVED]
  # - "// console.log"  # Comment out console.log
  # - null            # Delete the line after print() statements

# Multi-line blocks to remove
blocks:
  # - start: "/* DEBUG START */"
  #   end: "/* DEBUG END */"
  # - start: "### TEMP CODE START ###"
  #   end: "### TEMP CODE END ###"

# File extensions to process (optional)
extensions:
  - js
  - ts
  - py
  - rs
  - rb
  - md
  - json
  - toml
  - sh
  - tsx
  - mdx
  - yml
  - txt
  - gemspec
  - erb

# Directories to exclude (optional)
exclude:
  - node_modules
  - target
  - .git
  - __pycache__
